### ISSUE TITLE
你这是百度文字识别老用户的api，新用户不行吧

### ISSUE THREAD

**Issue by sampsonliu** [anhkgg/answerot#3]
你这是百度文字识别老用户的api，新用户不行吧？

**Comment by anhkgg** [comment]
我不清楚你说的新老用户的区别，API目前官网还有，所以目前是可以用的
另外我也不是老用户，再者你可以试一下看看是否可以使用

**Comment by CrazyEig** [comment]
不知道我显示
HTTP Error 401: Unauthorized
--
请检查网络
是不是api的问题

**Comment by anhkgg** [comment]
@CrazyEig 

![1](https://user-images.githubusercontent.com/9443285/35392075-91bf79b0-021b-11e8-8d9a-6d3c3b93b54b.png)

**Comment by anhkgg** [comment]
可以试用服务器[www.answerot.com](www.answerot.com)
