### ISSUE TITLE
这个高亮做的特别好，能不能做一个类似截图让用户自己选识别区域的功能，很多平台题目位置不一样，识别区域很重要

### ISSUE THREAD

**Issue by AUGUSTRUSH8** [anhkgg/answerot#4]

**Comment by anhkgg** [comment]
所以我做了不同平台的兼容处理，如果你有兴趣，可以麻烦给我提供一下其他平台的题目截图，我把他们都加上去，这样也不用用户来选择了

**Comment by AUGUSTRUSH8** [comment]
![uc](https://user-images.githubusercontent.com/29452599/35479250-bf01ab28-042d-11e8-83ce-5695032ea0bd.png)
![default](https://user-images.githubusercontent.com/29452599/35479251-bf44e76c-042d-11e8-8219-8f71de7e9bc5.png)
![-](https://user-images.githubusercontent.com/29452599/35479252-bf876a60-042d-11e8-86ec-9bddd6de5ad1.png)
![default](https://user-images.githubusercontent.com/29452599/35479253-bfcc9bda-042d-11e8-84f8-b2004c231f47.png)

**Comment by AUGUSTRUSH8** [comment]
以上几个分别是UC、蘑菇街、掌阅百万文豪和芝士超人的截屏，这是目前我有的（^^）

**Comment by anhkgg** [comment]
感谢提供，我这就更新上，到时还麻烦你测试下

**Comment by anhkgg** [comment]
已更新
